version: '3'
services:
  frontend:
    container_name: interview-frontend-app
    hostname: frontend
    image: interview-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend/static:/app/static
    depends_on:
      - backend
      - postgres
    networks:
      - interview

  backend:
    container_name: interview-backend-app
    hostname: backend
    image: interview-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - PG_CONNECTION_STRING=Server=postgres;Database=interview;Port=5432;User Id=postgres;Password=interview;
    depends_on:
      - postgres
    networks:
      - interview

  postgres:
    ports:
      - 5432:5432
    container_name: interview-postgresql
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=interview
    image: postgres:14.2
    networks:
      - interview

networks:
  interview:
